/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YY1rri3SiYJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Image from "next/image"

export function Landing() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-gradient-to-r from-[#4c51bf] to-[#6b46c1]">
        <div className="container px-4 md:px-6 text-white text-center">
          <div className="space-y-4">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
            Geocodificación Simplificada: Google Maps y OpenCage a Tu Servicio
            </h1>
            <p className="mx-auto max-w-[700px] text-lg md:text-xl">
            Sube tu archivo de Excel y deja que nuestra plataforma haga el trabajo pesado por ti. Con la potencia de las API de geocodificación de Google Maps y OpenCage, transformamos tus direcciones en coordenadas precisas y nombres de ubicación.
            </p>
            <div>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-white px-8 text-sm font-medium text-[#4c51bf] shadow transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                href="/googlegeocoding"
              >
                Try it Now
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#4c51bf] px-3 py-1 text-sm text-white">
                  Reverse Geocoding
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Convert Coordinates to Addresses
                </h2>
                <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Our powerful reverse geocoding capabilities allow you to seamlessly translate latitude and longitude
                  coordinates into human-readable addresses.
                </p>
              </div>
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#4c51bf] px-3 py-1 text-sm text-white">
                  Batch Processing
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Process Thousands of Locations at Once
                </h2>
                <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Streamline your workflows with our batch processing feature, enabling you to geocode multiple
                  locations in a single request.
                </p>
              </div>
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#4c51bf] px-3 py-1 text-sm text-white">
                  Customizable Results
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Tailor the Data to Your Needs
                </h2>
                <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Customize the geocoding results to include only the information you need, from detailed address
                  components to geographic coordinates.
                </p>
              </div>
            </div>
            <Image
              alt="Geocoding Illustration"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      {/* <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#4c51bf] px-3 py-1 text-sm text-white">Pricing</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Flexible Pricing for Every Need
                </h2>
                <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Choose from our range of pricing plans to find the perfect fit for your business or project.
                </p>
              </div>
              <div className="grid gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Starter</CardTitle>
                    <CardDescription>Perfect for small projects and personal use.</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="text-4xl font-bold">$9</div>
                    <div className="text-gray-500 dark:text-gray-400">per month</div>
                    <ul className="space-y-2 text-gray-500 dark:text-gray-400">
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        100 requests per month
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Basic geocoding capabilities
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Email support
                      </li>
                    </ul>
                    <Button>Get Started</Button>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Pro</CardTitle>
                    <CardDescription>Ideal for businesses and larger projects.</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="text-4xl font-bold">$49</div>
                    <div className="text-gray-500 dark:text-gray-400">per month</div>
                    <ul className="space-y-2 text-gray-500 dark:text-gray-400">
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        1,000 requests per month
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Reverse geocoding and batch processing
                      </li>
                      <li>
                        <CheckIcon className="mr-2 inline-block h-4 w-4 text-green-500" />
                        Priority email and chat support
                      </li>
                    </ul>
                    <Button>Get Started</Button>
                  </CardContent>
                </Card>
              </div>
            </div>
            <div className="space-y-4">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-[#4c51bf] px-3 py-1 text-sm text-white">Sign Up</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Join Our Geocoding Community
                </h2>
                <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Create an account and start using our powerful geocoding service today.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex flex-col space-y-2">
                  <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email" />
                  <Input className="max-w-lg flex-1" placeholder="Enter your password" type="password" />
                  <Button type="submit">Sign Up</Button>
                </form>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  By signing up, you agree to our
                  <Link className="underline underline-offset-2" href="#">
                    Terms of Service
                  </Link>
                  .
                </p>
              </div>
            </div>
          </div>
        </div>
      </section> */}
    </div>
  )
}

// function CheckIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <polyline points="20 6 9 17 4 12" />
//     </svg>
//   )
// }
